version: '3.9'

services:

  webapp:
    container_name: "dev_movie_api_app_cnt"
    env_file:
      - .env
    build:
      context: .
      dockerfile: "Dockerfile.dev"
    volumes:
      - ".:/application"
      - "/application/node_modules"
    ports:
      - "8080:8080"
