version: '3.9'

services:

  webapp:
    container_name: "prod_movie_api_app_cnt"
    env_file:
      - .env
    build:
      context: .
      dockerfile: "Dockerfile.prod"
    ports:
      - "8080:8080"
