version: '3.9'

services:

  server_app:
    container_name: "prod_movie_api_app_container"
    env_file:
      - .env
    build:
      context: .
      dockerfile: "Dockerfile.prod"
    ports:
      - "8080:8080"
